---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: reciping-ads-aws-secret
  namespace: reciping
spec:
  encryptedData:
    aws_access_key_id: AgBWbZ6Sb8a3nlKCb+WLQpVMQr6BMV0sPMM159/JTGbtEu0i3kh9/Rw6HLbI+sh6T3xvTS4lGyyrO8HtmRgwa8qQkCbqKaHT52GRW9WvXHcDtsVWl2t09vlhv3zpy5rZoISwlFu/BhNBXJ8uOF7NjrTqXbTQhhepU9KNnv5vloeJQ9iJ5wXG5mQAF+uoNUcEuWaSSV4VEmb5Ob4kkbKtm2h+R3Sci+HKaamqnUGG21OJhmlPN6XA/rllNsLyo3qIlW/+BvUpmScU/pKQxFLabkWKtyhf9rQWN+NjmQ4X7jKVcC2qKlblmLiwypxp32pRypCahsSbnJCZsHJ00hS7jOp0qI/4E1+RhEkF2+5fJn4ub+Epfx3ouiP3WDCNjl7MKqjag28e/TZ8RKT2jdVbjPcFh9Q/dEo+ml9/DcgKIoeRWHOz3AkTUcxaWnt4q9s+Ryazhk/a+sASF8xONcxw2VMhX/aPN49K2+kAmtJMtFFMY9yJIg9Lbs9MWEUXmmX1QBLEJNKGPkVpR4FDErUJuTGScti/tjAD9mxahKMw72qFBfz33euPvyX41Z2lloWTwve/XsAKLNSBy9rQJ5Q0DJa9QKjteRPw0FZQmKnWCTHMM3sToWETbMrIf9VmLJyLmms9B/b7gyxTCMJhVls+s8/AOuyLC+ADWAu90fqh2mo5LS+HAtMYfQ5c5uEtmBPmSyybevEHtWsKBVAGlxLZ4wG8/f5a5w==
    aws_secret_access_key: AgCICGzjSS3r8sOjhKwett9an2ONF7aW9F6FLh57V6KXHJRcZpXilhrsbJm90XNW7By1xFgl7qtSvI8Xregt5uT+Gr0KfS4dtmicEC4aO/wWAvQG6zs7dApM3EY+1cVlcp6MdMLPAQCGErwxS4aISHMOkWSu5UcjvWwzlSIVud3xWvnnZ3TJRdflLfJLQNLcHcjVaZ47lsqHZwHSPw1cSaM1Sk2QbhOKDFDkHKbuahTa2nx414CRkjGWJXYHAEGEcv41sHXedXdVjIk0KVEZjFWvVQ6kj0dRRXzQypXPzefhFUGpVPbPlRg/b0S8FhChdLttuQGDRKiEamUkNNDh/iLD6VlUYqEfdL3R56w8Lpov0GLk7Pl3HEPwBTS7grx5HvexCOtfNyGlthlcgTAIzKwvZX8HUZJjlU7UFyuAJebJFMoUzvKAu9PSMpcDNrVv/JgW+HdvFMQcb+L3YMK7G8/AcP16O2tnD3h6ZNlLOfBV1uUjfzK3wE0YnEceoPJylmHALnmTkroR2y0AFYhXQFOF861evrs2ZNS7VPtJvWmxE/Gc9BLQyGcKBaxkRFwMx7mptnN4Hq1iaMAEVscFAqmx10sJ3Zjq6u3PgRKd/2kyXKZn4v1li970lvJ+cAA5CkO0cquOmekC6jOp3nSbgOusy6Kn420FMqi3jZbq8uvsOjVaTXL5RgVGK3q/IT5ZLEo/5/e3lhfs1GXrhTtuq8EgaWn2i8IT32ZhzdGAQlj75GCFS52Dw6HbcA==
  template:
    metadata:
      creationTimestamp: null
      name: reciping-ads-aws-secret
      namespace: reciping
    type: Opaque
