apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway-service.fullname" . }}-config
  labels:
    app: {{ include "gateway-service.name" . }}
data:
  application-prod.yaml: |-
    server:
      port: 8090

    spring:
      application:
        name: gateway-service

      cloud:
        gateway:
      # default-filters removed due to expression error (responseTime not defined)
          routes:
            # Special route to expose user-service actuator via gateway without API prefix rewrite
            - id: user-service-actuator
              uri: http://reciping-user-service:8080
              predicates:
                - Path=/users/actuator/**
              filters:
                - RewritePath=/users/actuator/(?<segment>.*), /actuator/${segment}

            - id: user-service
              uri: http://reciping-user-service:8080
              predicates:
                - Path=/users/**
              filters:
                - RewritePath=/users/(?<segment>.*), /api/v1/users/${segment}

            - id: recipe-service
              uri: http://reciping-recipe-service:8081
              predicates:
                - Path=/recipes/**
              filters:
                - RewritePath=/recipes/(?<segment>.*), /api/v1/recipes/${segment}
            - id: like-service
              uri: http://reciping-like-service:8082
              predicates:
                - Path=/likes/**
              filters:
                - RewritePath=/likes/(?<segment>.*), /api/v1/likes/${segment}
            - id: search-service
              uri: http://reciping-search-service:8084
              predicates:
                - Path=/search/**
              filters:
                - RewritePath=/search/(?<segment>.*), /api/v1/search/${segment}
            - id: ad-service
              uri: http://reciping-ads-service:8085
              predicates:
                - Path=/ads/**
              filters:
                - RewritePath=/ads/(?<segment>.*), /api/v1/ads/${segment}
            - id: comment-service
              uri: http://reciping-comment-service:8086
              predicates:
                - Path=/comments/**
              filters:
                - RewritePath=/comments/(?<segment>.*), /api/v1/comments/${segment}
            - id: recommend-service
              uri: http://reciping-recommendation-service:8087
              predicates:
                - Path=/recommend/**
              filters:
                - RewritePath=/recommend/(?<segment>.*), /api/v1/recommend/${segment}

    management:
      endpoints:
        web:
          exposure:
            include: health,info

    jwt:
      secret:
        key: ${JWT_SECRET_KEY}
