# templates/service.yaml - gateway-service를 위한 Kubernetes Service 정의
# ClusterIP로 설정되어 있으며, Ingress를 통해 외부 노출됩니다

apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway-service.fullname" . }}
  labels:
    app: {{ include "gateway-service.name" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}  # 일반적으로 ClusterIP
  selector:
    app: {{ include "gateway-service.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}            # 서비스가 노출할 포트 (예: 8090)
      targetPort: {{ .Values.containerPort }}     # 실제 컨테이너에서 사용하는 포트
