# values.yaml은 Helm 템플릿에서 사용할 변수들의 기본값을 정의하는 곳입니다.
# 실무에서는 CI/CD 파이프라인 또는 ArgoCD를 통해 이 값을 환경별로 주입합니다.

replicaCount: 1  # 2개 이상으로 설정해 고가용성 보장

image:
  repository: 892117097999.dkr.ecr.ap-northeast-2.amazonaws.com/reciping-gateway-service
  tag: "v1.0.6"
  pullPolicy: IfNotPresent  # 로컬에 이미지가 없을 때만 풀

imagePullSecrets:
  - name: reciping-ecr-secret  # 프라이빗 레지스트리 인증이 필요하면 여기서 secret 이름 지정

containerPort: 8090  # Spring Boot 애플리케이션이 사용하는 포트

service:
  type: ClusterIP  # 클러스터 내부에서만 접근 가능 (Ingress 통해 외부 노출)
  port: 80

metrics:
  prometheus:
    enabled: true
    path: /actuator/prometheus
    port: 8090
    podMonitor:
      enabled: true    # kube-prometheus-stack 사용 시 true (CRD 미존재 시 템플릿이 자동 Skip)

ingress:
  enabled: true
  className: alb  # ALB Ingress Controller 사용 시 클래스 이름은 "alb"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing  # 퍼블릭 ALB
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:892117097999:certificate/c6a16497-4da7-4cce-8fc7-29a5a5dc3e36
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/group.name: reciping
    alb.ingress.kubernetes.io/success-codes: "200-399"
  hosts:
    - host: api.reciping.kr
      paths:
        - path: /
          pathType: Prefix
  tls: []  # ALB에서는 ACM으로 SSL 처리하므로 따로 tls 설정은 비워둠

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

secretName: reciping-gateway-secret  # JWT를 포함한 Secret 이름

nodeSelector: {}

tolerations: []

affinity: {}
