replicaCount: 2

image:
  repository: 892117097999.dkr.ecr.ap-northeast-2.amazonaws.com/reciping-user-service
  tag: v1.0.9
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: reciping-ecr-secret

containerPort: 8080

service:
  port: 8080

database:
  url: "jdbc:postgresql://<rds-endpoint>:5432/app"   # 실제 RDS 엔드포인트로 교체 필요
  username: "appuser"
  password: "changeme-strong-password"

metrics:
  prometheus:
    enabled: true
    path: /actuator/prometheus
    port: 8080
    podMonitor:
      enabled: true

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi