replicaCount: 2

# 팀 태그(모니터링/알람 라우팅에 사용)
team: user

image:
  repository: 892117097999.dkr.ecr.ap-northeast-2.amazonaws.com/reciping-user-service
  tag: v1.0.12
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: reciping-ecr-secret

containerPort: 8080

service:
  port: 8080

database:
  url: "jdbc:postgresql://reciping-postgres.cfmw20sgimj0.ap-northeast-2.rds.amazonaws.com:5432/app"
  username: "appuser"
  password: "changeme-strong-password"

metrics:
  prometheus:
    enabled: true
    path: /actuator/prometheus
    port: 8080
    podMonitor:
      enabled: true

# 배포 전략 실험 설정
strategy:
  # canary | blueGreen | rollingUpdate.
  type: canary
  blueGreen:
    autoPromotionEnabled: false
    autoPromotionSeconds: 0
    scaleDownDelaySeconds: 30
    previewReplicaCount: 2
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# 배포 중 연결 드레인 및 종료 유예 시간 설정(실험용)
lifecycle:
  preStopSleepSeconds: 30
  terminationGraceSeconds: 60