# Spring Boot의 application-prod.yaml 설정 파일을 Kubernetes ConfigMap으로 주입하기 위한 템플릿입니다.
# Pod에서 이 파일을 마운트하여 Spring Boot가 실행 시 참조할 수 있도록 합니다.

apiVersion: v1
kind: ConfigMap
metadata:
  name: like-service-config  # 이 이름은 rollout.yaml에서 volumeMount 시 참조됩니다
  labels:
    app: like-service

# stringData는 사람이 읽기 쉬운 방식으로 설정을 삽입할 수 있게 해줍니다.
# 여기서는 Helm multi-line block literal (|-) 을 사용하여 YAML 원본 파일을 통째로 주입합니다.
# 띄어쓰기 및 포맷이 실제 application-prod.yaml과 동일해야 합니다.
data:
  application-prod.yaml: |-
    spring:
      application:
        name: reciping-like-service-BE
      data:
        mongodb:
          uri: mongodb://recipingadmin:changeme@reciping-nosql.cluster-c7wokrloy1td.ap-northeast-2.docdb.amazonaws.com:37017/like_service_db
      jackson:
        serialization:
          indent_output: true

    jwt:
      secret:
        key: ${JWT_SECRET_KEY}

    management:
      endpoints:
        web:
          exposure:
            include: health
