apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "like-service.fullname" . }}-config
  labels:
    # 이 ConfigMap이 속한 Helm 차트와 릴리스 식별용 라벨
    app.kubernetes.io/name: {{ include "like-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  application-prod.yaml: |-
    server:
      port: 8082

    spring:
      application:
        name: reciping-like-service-BE
      data:
        mongodb:
          # 환경변수로 주입되는 DocumentDB 접속 URI 사용
          uri: ${DOCDB_URI}
          database: {{ .Values.docdb.database | default "like_service_db" }}
          auto-index-creation: true

      jackson:
        serialization:
          indent_output: true

    jwt:
      secret:
        key: ${JWT_SECRET_KEY}

    management:
      endpoints:
        web:
          exposure:
            include: health,prometheus

    endpoint:
      health:
        show-details: always