apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "like-service.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "like-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  application-prod.yaml: |-
    server:
      port: 8082

    spring:
      application:
        name: reciping-like-service-BE
      data:
        mongodb:
          uri: ${DOCDB_URI}
          database: {{ .Values.docdb.database | default "like_service_db" }}
          auto-index-creation: true
          ssl:
            enabled: true
            invalid-hostname-allowed: false

      jackson:
        serialization:
          indent_output: true

    jwt:
      secret:
        key: ${JWT_SECRET_KEY}

    management:
      endpoints:
        web:
          exposure:
            include: health,prometheus

    endpoint:
      health:
        show-details: always