apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "like-service.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "like-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  application-prod.yaml: |-
    server:
      port: 8082

    spring:
      application:
        name: reciping-like-service-BE
      data:
        mongodb:
          uri: mongodb://recipingadmin:changeme@reciping-nosql.cluster-c7wokrloy1td.ap-northeast-2.docdb.amazonaws.com:37017/like_service_db?ssl=true&retryWrites=false&tlsAllowInvalidHostnames=true
      jackson:
        serialization:
          indent_output: true

    jwt:
      secret:
        key: ${JWT_SECRET_KEY}

    management:
      endpoints:
        web:
          exposure:
            include: health

    endpoint:
    health:
      show-details: always