{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "like-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "like-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: {{- if eq .Values.workload.kind "Deployment" -}}apps/v1{{- else -}}argoproj.io/v1alpha1{{- end }}
    kind: {{- if eq .Values.workload.kind "Deployment" -}}Deployment{{- else -}}Rollout{{- end }}
    name: {{ include "like-service.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  {{- if .Values.hpa.cpu.enabled }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.cpu.targetAverageUtilization }}
  {{- end }}
  {{- if .Values.hpa.memory.enabled }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.memory.targetAverageUtilization }}
  {{- end }}
{{- end }}

