{{- if eq .Values.workload.kind "Rollout" }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "like-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "like-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "like-service.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "like-service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- if .Values.metrics.prometheus.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/path: {{ .Values.metrics.prometheus.path | quote }}
        prometheus.io/port: {{ .Values.metrics.prometheus.port | quote }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.lifecycle.terminationGraceSeconds }}
      containers:
        - name: like-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          args:
            - "--spring.config.additional-location=optional:classpath:/,optional:file:/config/"
            - "--spring.profiles.active=prod"
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - sleep {{ .Values.lifecycle.preStopSleepSeconds }}
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "like-service.fullname" . }}-secret
                  key: jwt-secret-key
            - name: DOCDB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "like-service.fullname" . }}-secret
                  key: docdb-uri
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "like-service.fullname" . }}-config
            items:
              - key: application-prod.yaml
                path: application-prod.yaml
  strategy:
    {{- if eq .Values.strategy.type "canary" }}
    canary:
      steps:
        {{- range $i, $s := .Values.strategy.canary.steps }}
        - setWeight: {{ $s.weight }}
        {{- if $s.pause }}
        - pause: { duration: {{ $s.pause }} }
        {{- end }}
        {{- end }}
    {{- else if eq .Values.strategy.type "blueGreen" }}
    blueGreen:
      activeService: {{ include "like-service.fullname" . }}
      previewService: {{ include "like-service.fullname" . }}-preview
      autoPromotionEnabled: {{ .Values.strategy.blueGreen.autoPromotionEnabled }}
      autoPromotionSeconds: {{ .Values.strategy.blueGreen.autoPromotionSeconds }}
      scaleDownDelaySeconds: {{ .Values.strategy.blueGreen.scaleDownDelaySeconds }}
      previewReplicaCount: {{ .Values.strategy.blueGreen.previewReplicaCount }}
    {{- else }}
    rollingUpdate:
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
    {{- end }}
{{- end }}