# Kubernetes Secret 리소스를 정의하는 템플릿입니다.
# 이 리소스는 JWT_SECRET_KEY와 같이 민감한 환경변수를 Helm을 통해 주입하기 위해 사용됩니다.
# 실제 값은 values.yaml에 정의되어 있으며, Helm 템플릿이 이 값을 참조하여 Secret을 생성합니다.

apiVersion: v1
kind: Secret
metadata:
  name: like-service-secret  # 이 이름은 rollout.yaml에서 valueFrom.secretKeyRef.name으로 참조됨
  labels:
    app: like-service  # 리소스 식별용 라벨

type: Opaque  # 기본적인 문자열 기반 Secret 유형입니다 (base64 인코딩 아님 - stringData 사용 시)

stringData:
  jwt-secret-key: {{ .Values.secret.jwtSecretKey | quote }}  # values.yaml의 값이 여기로 들어옵니다

  # 주의: stringData는 값을 base64 인코딩하지 않고 그대로 입력받아 base64로 자동 인코딩함
  #      → secret.data가 아니라 secret.stringData를 쓰는 이유는 사람이 읽기 쉬우면서 GitOps에도 적합하기 때문입니다
