apiVersion: v1
kind: Secret
metadata:
  name: {{ include "like-service.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "like-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  jwt-secret-key: {{ .Values.secret.jwtSecretKey | quote }}
  # 앱에서 spring.data.mongodb.uri 로 사용할 전체 접속 URI 조합
  {{- $tls := ternary "true" "true" .Values.docdb.tls.insecure }}
  {{- $allowInvalidHostnames := ternary "true" "false" .Values.docdb.tls.allowInvalidHostnames }}
  docdb-uri: {{ printf "mongodb://%s:%s@%s:%d/%s?tls=%s&tlsAllowInvalidHostnames=%s&retryWrites=false&readPreference=secondaryPreferred&replicaSet=rs0" .Values.docdb.username .Values.docdb.password .Values.docdb.host (.Values.docdb.port | int) (.Values.docdb.database | default "like_service_db") $tls $allowInvalidHostnames | quote }}