apiVersion: v1
kind: Secret
metadata:
  name: {{ include "like-service.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "like-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  jwt-secret-key: {{ .Values.secret.jwtSecretKey | quote }}