apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: service-temp-rules
  namespace: monitoring
spec:
  groups:
    - name: http-baseline-threshold
      rules:
        - alert: HighErrorRate
          expr: |
            sum by (reciping_team, reciping_service) (
              rate(http_server_requests_seconds_count{status=~"5.."}[5m])
            )
            /
            sum by (reciping_team, reciping_service) (
              rate(http_server_requests_seconds_count[5m])
            ) > 0.07
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "High 5xx error rate"
            description: "Team {{ $labels.reciping_team }}, svc {{ $labels.reciping_service }} > 7% for 10m"

        - alert: ErrorRateAnomaly
          expr: |
            (
              sum by (reciping_team, reciping_service) (rate(http_server_requests_seconds_count{status=~"5.."}[5m]))
              /
              sum by (reciping_team, reciping_service) (rate(http_server_requests_seconds_count[5m]))
            )
            -
            avg_over_time(
              (
                sum by (reciping_team, reciping_service) (rate(http_server_requests_seconds_count{status=~"5.."}[5m]))
                /
                sum by (reciping_team, reciping_service) (rate(http_server_requests_seconds_count[5m]))
              )[6h:5m]
            )
            >
            3 * stddev_over_time(
              (
                sum by (reciping_team, reciping_service) (rate(http_server_requests_seconds_count{status=~"5.."}[5m]))
                /
                sum by (reciping_team, reciping_service) (rate(http_server_requests_seconds_count[5m]))
              )[6h:5m]
            )
            and
            sum by (reciping_team, reciping_service) (rate(http_server_requests_seconds_count[5m])) > 0.1
          for: 10m
          labels:
            severity: critical
          annotations:
            summary: "Error rate anomaly"
            description: "Team {{ $labels.reciping_team }}, svc {{ $labels.reciping_service }} anomaly vs last 6h baseline"
