apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: service-anomaly-rules
  namespace: monitoring
spec:
  groups:
    - name: http-anomaly
      rules:
        - alert: ServiceTrafficAnomaly
          expr: |
            (
              sum by (reciping_team,reciping_service) (
                rate(http_server_requests_seconds_count{uri!~"/actuator/.*"}[5m])
              )
              -
              avg_over_time((
                sum by (reciping_team,reciping_service) (
                  rate(http_server_requests_seconds_count{uri!~"/actuator/.*"}[5m])
                )
              )[1h])
            )
            /
            clamp_min(stddev_over_time((
              sum by (reciping_team,reciping_service) (
                rate(http_server_requests_seconds_count{uri!~"/actuator/.*"}[5m])
              )
            )[1h]), 1e-6)
            > 3
            and
            sum by (reciping_team,reciping_service) (
              rate(http_server_requests_seconds_count{uri!~"/actuator/.*"}[5m])
            ) > 0.1
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "[경고] 트래픽 이상 감지"
            description: "팀={{ $labels.reciping_team }}, 서비스={{ $labels.reciping_service }}의 RPS가 최근 1시간 기준선 대비 3σ 이상 벗어났습니다(10분 지속)."

        - alert: ServiceErrorRateAnomaly
          expr: |
            (
              (
                sum by (reciping_team,reciping_service) (
                  rate(http_server_requests_seconds_count{status=~"5..",uri!~"/actuator/.*"}[5m])
                )
                /
                sum by (reciping_team,reciping_service) (
                  rate(http_server_requests_seconds_count{uri!~"/actuator/.*"}[5m])
                )
              )
              -
              avg_over_time((
                (
                  sum by (reciping_team,reciping_service) (
                    rate(http_server_requests_seconds_count{status=~"5..",uri!~"/actuator/.*"}[5m])
                  )
                  /
                  sum by (reciping_team,reciping_service) (
                    rate(http_server_requests_seconds_count{uri!~"/actuator/.*"}[5m])
                  )
                )
              )[1h])
            )
            /
            clamp_min(stddev_over_time((
              (
                sum by (reciping_team,reciping_service) (
                  rate(http_server_requests_seconds_count{status=~"5..",uri!~"/actuator/.*"}[5m])
                )
                /
                sum by (reciping_team,reciping_service) (
                  rate(http_server_requests_seconds_count{uri!~"/actuator/.*"}[5m])
                )
              )
            )[1h]), 1e-6)
            > 3
            and
            sum by (reciping_team,reciping_service) (
              rate(http_server_requests_seconds_count{uri!~"/actuator/.*"}[5m])
            ) > 0.1
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "[경고] 오류율 이상 감지"
            description: "팀={{ $labels.reciping_team }}, 서비스={{ $labels.reciping_service }}의 오류율이 최근 1시간 기준선 대비 3σ 이상 벗어났습니다(10분 지속)."

