apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: service-anomaly-rules
  namespace: monitoring
spec:
  groups:
    - name: http-anomaly
      rules:
        - alert: ServiceTrafficAnomaly
          expr: |
            sum by (reciping_team,reciping_service) (
              rate(http_server_requests_seconds_count{uri!~"/actuator/.*"}[5m])
            ) > 1e12
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "[경고] 트래픽 이상 감지"
            description: "팀={{ $labels.reciping_team }}, 서비스={{ $labels.reciping_service }}의 RPS 임시 임계치 초과(밸리데이션용 단순식)."

        - alert: ServiceErrorRateAnomaly
          expr: |
            (
              sum by (reciping_team,reciping_service) (
                rate(http_server_requests_seconds_count{status=~"5..",uri!~"/actuator/.*"}[5m])
              )
              /
              sum by (reciping_team,reciping_service) (
                rate(http_server_requests_seconds_count{uri!~"/actuator/.*"}[5m])
              )
            ) > 2
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "[경고] 오류율 이상 감지"
            description: "팀={{ $labels.reciping_team }}, 서비스={{ $labels.reciping_service }}의 오류율 임시 임계치 초과(밸리데이션용 단순식)."

