replicaCount: 2  # 기본 레플리카 수

image:
  repository: 082808744580.dkr.ecr.ap-northeast-2.amazonaws.com/reciping-like-service
  tag: v1.0.2
  pullPolicy: IfNotPresent  # 기본 이미지 풀 정책

service:
  port: 8082  # Spring Boot의 포트 (application.yml 기준)

env:
  profile: prod  # --spring.profiles.active 값

secret:
  jwtSecretKey: "m5M/3YqO8kB/32Xu0/AlU8TKtsKhXHXuRAm5XGvx786uTj3+BpN1RAA65tJvbOg1pZuVG+TqMyFk2XRL3rU7HA=="  # ${JWT_SECRET_KEY}로 사용되는 값

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
