replicaCount: 2

image:
  repository: 082808744580.dkr.ecr.ap-northeast-2.amazonaws.com/reciping-like-service
  tag: v1.0.5
  pullPolicy: IfNotPresent

service:
  port: 8082

secret:
  jwtSecretKey: "m5M/3YqO8kB/32Xu0/AlU8TKtsKhXHXuRAm5XGvx786uTj3+BpN1RAA65tJvbOg1pZuVG+TqMyFk2XRL3rU7HA=="

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi