apiVersion: batch/v1
kind: CronJob
metadata:
  name: ads-ab-mock
  namespace: reciping
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: pusher
              image: curlimages/curl:8.5.0
              env:
                - name: PG
                  value: http://mock-pushgateway.monitoring:9091
              command: ["sh","-c"]
              args:
                - |
                  ts=$(date +%s)
                  cat <<EOF >/tmp/metrics.prom
                  # TYPE ads_ab_event_total counter
                  ads_ab_event_total{reciping_team="ads",reciping_service="reciping-ads-service",scenario="home",ab_group="CONTROL",type="IMPRESSION"} 20
                  ads_ab_event_total{reciping_team="ads",reciping_service="reciping-ads-service",scenario="home",ab_group="TREATMENT",type="IMPRESSION"} 20
                  ads_ab_event_total{reciping_team="ads",reciping_service="reciping-ads-service",scenario="home",ab_group="CONTROL",type="CLICK"} 1
                  ads_ab_event_total{reciping_team="ads",reciping_service="reciping-ads-service",scenario="home",ab_group="TREATMENT",type="CLICK"} 2
                  # TYPE ads_recommendation_fallback_total counter
                  ads_recommendation_fallback_total{reciping_team="ads",reciping_service="reciping-ads-service"} 1
                  # TYPE ads_serve_duration_seconds histogram
                  ads_serve_duration_seconds_bucket{le="0.05",reciping_team="ads",reciping_service="reciping-ads-service",scenario="home",ab_group="CONTROL"} 5
                  ads_serve_duration_seconds_bucket{le="0.1",reciping_team="ads",reciping_service="reciping-ads-service",scenario="home",ab_group="CONTROL"} 10
                  ads_serve_duration_seconds_bucket{le="0.25",reciping_team="ads",reciping_service="reciping-ads-service",scenario="home",ab_group="CONTROL"} 15
                  ads_serve_duration_seconds_bucket{le="+Inf",reciping_team="ads",reciping_service="reciping-ads-service",scenario="home",ab_group="CONTROL"} 20
                  ads_serve_duration_seconds_bucket{le="0.05",reciping_team="ads",reciping_service="reciping-ads-service",scenario="home",ab_group="TREATMENT"} 6
                  ads_serve_duration_seconds_bucket{le="0.1",reciping_team="ads",reciping_service="reciping-ads-service",scenario="home",ab_group="TREATMENT"} 12
                  ads_serve_duration_seconds_bucket{le="0.25",reciping_team="ads",reciping_service="reciping-ads-service",scenario="home",ab_group="TREATMENT"} 18
                  ads_serve_duration_seconds_bucket{le="+Inf",reciping_team="ads",reciping_service="reciping-ads-service",scenario="home",ab_group="TREATMENT"} 24
                  ads_serve_duration_seconds_count{reciping_team="ads",reciping_service="reciping-ads-service",scenario="home",ab_group="CONTROL"} 20
                  ads_serve_duration_seconds_sum{reciping_team="ads",reciping_service="reciping-ads-service",scenario="home",ab_group="CONTROL"} 2.4
                  ads_serve_duration_seconds_count{reciping_team="ads",reciping_service="reciping-ads-service",scenario="home",ab_group="TREATMENT"} 24
                  ads_serve_duration_seconds_sum{reciping_team="ads",reciping_service="reciping-ads-service",scenario="home",ab_group="TREATMENT"} 2.6
                  EOF
                  curl -sS --data-binary @/tmp/metrics.prom $PG/metrics/job/ads-ab-mock/instance/mock-$ts
