apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-pushgateway
  namespace: monitoring
  labels:
    app: mock-pushgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-pushgateway
  template:
    metadata:
      labels:
        app: mock-pushgateway
    spec:
      containers:
        - name: pushgateway
          image: prom/pushgateway:v1.7.0
          ports:
            - containerPort: 9091
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: mock-pushgateway
  namespace: monitoring
  labels:
    app: mock-pushgateway
spec:
  selector:
    app: mock-pushgateway
  ports:
    - name: http
      port: 9091
      targetPort: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mock-pushgateway
  namespace: monitoring
  labels:
    app: mock-pushgateway
spec:
  selector:
    matchLabels:
      app: mock-pushgateway
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: http
      interval: 30s
