apiVersion: batch/v1
kind: CronJob
metadata:
  name: user-traffic
  namespace: reciping
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: curl
            image: curlimages/curl:8.5.0
            command: ["sh","-c"]
            args:
              - |
                BASE="http://reciping-user-service.reciping:8080"
                urls="\
                  $BASE/api/v1/users/signup \
                  $BASE/api/v1/users/123/created-at \
                  $BASE/api/v1/users/me \
                  $BASE/api/v1/mypage \
                  $BASE/api/v1/mypage/bookmarks \
                  $BASE/api/v1/auth/refresh \
                  $BASE/login"
                for u in $urls; do
                  for i in $(seq 1 12); do
                    curl -s -o /dev/null -w "%{http_code}\n" "$u" || true
                    sleep 0.25
                  done
                done
