apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "user-service.fullname" . }}
  namespace: reciping
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "user-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "user-service.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          args:
            - "--spring.config.additional-location=optional:classpath:/,optional:file:/config/"
            - "--spring.profiles.active=prod"
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: reciping-user-secret
                  key: jwt_secret_key
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "user-service.fullname" . }}-config

  strategy:
    canary:
      steps:
        - setWeight: 30
        - pause: { duration: 30s }
        - setWeight: 60
        - pause: { duration: 30s }
        - setWeight: 100
