apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: reciping
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-preview
  namespace: reciping
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
