server:
  ingress:
    enabled: true
    ingressClassName: alb
    hostname: argocd.reciping.kr
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80, "HTTPS": 443}]'
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:082808744580:certificate/f7c5777b-0bf6-4d3a-b9da-6e4b14aa0144
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/backend-protocol: HTTP
    tls: true
    paths:
      - /
    pathType: Prefix

  service:
    type: ClusterIP
    servicePortHttp: 80
    servicePortHttps: 443

  extraArgs:
    - --insecure

dex:
  enabled: false